spring:
  application:
    name: order-service

  config:
    import: "configserver:http://localhost:8888"

#resilience4j:
#  circuitbreaker:
#    circuit-breaker-aspect-order: 1
#  ratelimiter:
#    rate-limiter-aspect-order: 2



